import { IRANSansWeb, IRANYekanWeb } from "@/styles/fonts";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${IRANSansWeb.className} ${IRANSansWeb.variable} ${IRANYekanWeb.variable}`}>{children}</body>
    </html>
  );
}
